# module "gcp_sap_hanasu1" {
#   source                     = "../modules/sap_hana"
#   subnetwork                 = "/projects/internal-naoxyatraininghost/regions/northamerica-northeast1/subnetworks/labnan1"
#   linux_image_family         = "rhel-8-1-sap-ha"
#   linux_image_project        = "rhel-sap-cloud"
#   instance_name              = "btln008580"
#   instance_type              = "n1-highmem-32"
#   project_id                 = "internal-naoxyatrainingservice"
#   region                     = "northamerica-northeast1"
#   zone                       = "northamerica-northeast1-b"
#   service_account_email      = "test-sap-telus@internal-naoxyatrainingservice.iam.gserviceaccount.com"
# #   boot_disk_type             = "pd-standard"
#   boot_disk_type             = "pd-balanced"
#   boot_disk_size             = 30
#   autodelete_disk            = "true"
#   #  pd_ssd_size                = 834
#   #  pd_hdd_size                = 416
# #   sap_hana_deployment_bucket = var.sap_hana_deployment_bucket
#   sap_hana_deployment_bucket = "oxya-lab-cds/HANA20_SPS05"
#   sap_deployment_debug       = "false"
#   post_deployment_script     = ""
#   startup_script             = file("../modules/sap_hana/files/startup.sh")
#   sap_hana_sid               = "NH1"
#   sap_hana_instance_number   = 12
#   sap_hana_sidadm_password   = "Starwars2020"
#   sap_hana_system_password   = "Starwars2020"
#   network_tags               = [ "sap", "internet", "ext-adm" ]
#   sap_hana_sidadm_uid        = 1202
#   sap_hana_sapsys_gid        = 241
#   instance_internal_ip       = "10.10.30.155"
#   public_ip                  = "false"
#   address_name               = ""
#   disk_name_0                = "btln008580"
#   disk_name_1                = "btln008580"
# #   sap_hana_scaleout_nodes    = 0
# #   sap_hana_backup_bucket     = "test-eso-bck"
# }
